---
dark_humor_philosophy_task:
  description: >
    Choose one key philosophical idea from ancient Cynicism or Stoicism. Take inspiration from famous philosophers from these 2 school of thoughts. 
    Create a short blog post that illustrates the chosen idea using a modern-day anecdote. 
    Incorporate sharp societal critique, dark humor, and a writing style inspired by 
    Samuel L. Jackson in Pulp Fiction. Feel free to use creative storytelling, 
    fictional dialogues, or satire.
    Your stories don't explicitly reference stoics, or cynics, you illustrates the ideas without blunt references like "Gotta love the Stoics" or "let me drop some Cynic wisdom on you", you are more subtle and let the ideas speak for themselves.
  expected_output: > 
    The output is a 2–3 paragraph blog post that combines one ancient Greek philosophical idea with 
    modern observations, written in a darkly humorous and foul-mouthed tone. The output 
    should be thought-provoking, entertaining, and critical of societal norms.
    The Output MUST be a well formatted HTML content, optimize for easy reading.
  async_execution: false
  agent: dark_humor_philosopher

publish_blog_post_task:
  description: >
    Automatically publish the generated blog post.
  expected_output: > 
    The blog post is successfully published using BlogTool. you MUST call BlogTool with the params "title" and "html_content".
  async_execution: false
  agent: website_publishing_specialist
  context:
  - dark_humor_philosophy_task
